def get_quote_of_satoshi(random_integer):
    quotes = {1:  "I didn’t really make that statement as strong as I could have. The requirement is that the good guys collectively have more CPU power than any single attacker.",
              2:  "I don’t think he could make as much money trying to pull a cardingscheme like that as he could by generating bitcoins.",
              3:  "Governments are good at cutting off the heads of a centrally controlled networks like Napster, but pure P2P networks like Gnutella and Tor seem to be holding their own.",
              4:  "The difficulty increases proportionally to keep the total new production constant. Thus, it is known in advance how many new bitcoins will be created every year in the future.",
              5:  "If the supply of money increases at the same rate that the number of people using it increases, prices remain stable. If it does not increase as fast as demand, there will be deflation and early holders of money will see its value increase.",
              6:  "Coins have to get initially distributed somehow, and a constant rate seems like the best formula.",
              7:  "I actually did this kind of backwards. I had to write all the code before I could convince myself that I could solve every problem, then I wrote the paper",
              8:  "The proof-of-work chain is the solution to the synchronisation problem, and to knowing what the globally shared view is without having to trust anyone.",
              9:  "The proof-of-work chain is itself self-evident proof that it came from the globally shared view. Only the majority of the network together has enough CPU power to generate such a difficult chain of proof-of-work",
              10: "With the transaction fee based incentive system I recently posted, nodes would have an incentive to include all the paying transactions they receive.",
              11: "It’s very attractive to the libertarian viewpoint if we can explain it properly. I’m better with code than with words though.",
              12: "It’s not pseudonymous in the sense of nyms identifying people, but it is at least a little pseudonymous in that the next action on a coin can be identified as being from the owner of that coin.",
              13: "If the real transaction reaches 90% and the double-spent tx reaches 10%, the double-spender only gets a 10% chance of not paying, and 90% chance his money gets spent. For almost any type of goods, that’s not going to be worth it for the scammer.",
              14: "When that runs out, the system can support transaction fees if needed. It’s based on open market competition, and there will probably always be nodes willing to process transactions for free.",
              15: "Total circulation will be 21,000,000 coins. It’ll be distributed to network nodes when they make blocks, with the amount cut in half every 4 years",
              16: "[...]after more than a decade of failed Trusted Third Party based systems (Digicash, etc), they see it as a lost cause. I hope they can make the distinction that this is the first time I know of that we’re trying a non-trust-based system.",
              17: "Interestingly, one of the e-gold systems already has a form of spam called “dusting”. Spammers send a tiny amount of gold dust in order to put a spam message in the transaction’s comment field.",
              18: "I’ve developed a new open source P2P e-cash system called Bitcoin. It’s completely decentralized, with no central server or trusted parties, because everything is based on crypto proof instead of trust.",
              19: "The root problem with conventional currency is all the trust that’s required to make it work. The central bank must be trusted notto debase the currency, but the history of fiat currencies is full of breaches of that trust.",
              20: "Banks must be trusted to hold our money and transfer it electronically, but they lend it out in waves of credit bubbles with barely a fraction in reserve.",
              21: "Their (banks) massive overhead costs make micropayments impossible.",
              22: "Before strong encryption, users had to rely on password protection to secure their files, placing trust in the system administrator to keep their information private.",
              23: "Then strong encryption became availableto the masses, and trust was no longer required. Data could be secured in a way that was physically impossible for others toaccess, no matter for what reason, no matter how good the excuse, no matter what.",
              24: "With e-currency based on cryptographic proof, without the need to trust a third party middleman, money can be secure and transactions effortless.",
              25: "Bitcoin’s solution is to use a peer-to-peer network to check for doublespending. In a nutshell, the network works like a distributed timestamp server, stamping the first transaction tospend a coin.",
              26: "A lot of people automatically dismiss e-currency as a lost cause because of all the companies that failed since the 1990’s. I hope it’s obvious it was only the centrally controlled nature of those systems that doomed them.",
              27: "I think this is the first time we’re trying a decentralized, non-trust-based system.",
              28: "Indeed, Bitcoin is a distributed secure timestamp server for transactions",
              29: "The possibility to be anonymous or pseudonymous relies on you not revealing any identifying information about yourself in connection with the bitcoin addresses you use.",
              30: "For greater privacy, it’s best to use bitcoin addresses only once.",
              31: "Since the effective circulation is reduced, all the remaining coins are worth slightly more. It’s the opposite of when a government prints money and the value of existing money goes down.",
              32: "The Bitcoin network has been running for almost a year now. The design and coding started in 2007.",
              33: "Computers have to get about 2^200 times faster before that starts to be a problem. Someone with lots of compute power could makemore money by generating than by trying to steal.",
              34: "If SHA-256 became completely broken, I think we could come to some agreement about what the honest block chain was beforethe trouble started, lock that in and continue from there with a new hash function.",
              35: "SHA256 is not like the step from 128 bit to 160 bit.SHA256 is not going to be broken by Moore’s law computational improvements in our lifetimes. If it’s going to get broken, it’ll be by some breakthrough cracking method.",
              36: "[...]the core design was set in stone for the rest of its lifetime. Because of that, I wanted to design it to support every possible transaction type I could think of",
              37: "At some point I became convinced there was a way to do this without any trust required at all and couldn’t resist to keep thinking about it. Much more of the work was designing than coding.",
              38: "The design outlines a lightweight client that does not need the full block chain. In the design PDF it’s called Simplified Payment Verification.",
              39: "I anticipate there will never be more than 100K nodes, probably less. It will reach an equilibrium where it’s not worth it for more nodes to join in. The rest will be lightweight clients, which could be millions.",
              40: "Whatever size micropayments you need will eventually be practical. I think in 5 or 10 years, the bandwidth and storage willseem trivial.",
              41: "A transaction can be written that requires two signatures to spend it next. You write a payment that requires the signature of boththe recipient and the sender to spend it.",
              42: "It’s the same situation as gold and gold mining. The marginal cost of gold mining tends to stay near the price of gold. Gold miningis a waste, but that waste is far less than the utility of having gold available as a medium of exchange.",
              43: "The utility of the exchanges made possible by Bitcoin will far exceed the cost of electricity used. Therefore, not having Bitcoin would be the net waste.",
              44: "Bitcoin generation should end up where it’s cheapest. Maybe that will be in cold climates where there’s electric heat, where it would be essentially free.",
              45: "[...]imagine there was a base metal as scarce as gold but with the following properties: boring grey in colour, not a good conductor of electricity [...] and one special, magical property: can be transported over a communications channel",
              46: "Bitcoins have no dividend or potential future dividend, therefore not like a stock. More like a collectible or commodity.",
              47: "If there’s going to be a message system, it should be a separate system parallel to the bitcoin network. Messages should not be recorded in the block chain.",
              48: "I make this appeal to WikiLeaks not to try to use Bitcoin. Bitcoin is a small beta community in its infancy. You would not stand to get more than pocket change, and the heat you would bring would likely destroy us at this stage.",
              49: "I wish you wouldn’t keep talking about me as a mysterious shadowy figure, the press just turns that into a pirate currency angle",
              50: "It would have been nice to this attention in any other context. WikiLeaks has kicked the hornet's nest, and the swarm is headed towards us.",
              51: "I’ve moved on to other things and probably won’t be around in the future.",
              52: "The Times 03/Jan/2009 Chancellor on brink of second bailout for banks.",
              53: "If you don’t believe it or don’t get it, I don’t have the time to try to convince you, sorry.",
              54: "Lost coins only make everyone else’s coins worth slightly more.  Think of it as a donation to everyone.",
              55: "In a few decades when the reward gets too small, the transaction fee will become the main compensation for [mining] nodes. I’m sure that in 20 years there will either be very large transaction volume or no volume.",
              56: "The address space is effectively unlimited.  It doesn’t hurt anyone, so generate all you want.",
              57: "This isn’t the kind of software where we can leave so many unresolved bugs that we need a tracker for them.",
              58: "Bitcoin would be convenient for people who don’t have a credit card or don’t want to use the cards they have.",
              59: "When someone tries to buy all the world’s supply of a scarce asset, the more they buy the higher the price goes. At some point, it gets too expensive for them to buy any more.",
              60: "We can win a major battle in the arms race and gain a new territory of freedom for several years.",
              61: "I don't believe a second, compatible implementation of Bitcoin will ever be a good idea.",
              62: "It doesn't matter who tells you a longest chain, the proof-of-work speaks for itself.",
              63: "You should never delete a wallet.",
              64: "For greater privacy, it's best to use bitcoin addresses only once.",
              65: "0/unconfirmed transactions [...] counting them as balance or spending them is premature.",
              66: "This is why people hate C++",
              67: "Never go to sea with two chronometers; take one or three.",
              68: "Bitcoin is an implementation of Wei Dai's b-money proposal [...] and Nick Szabo's Bitgold proposal[...].",
              69: "The more burden it is to run a node, the fewer nodes there will be. Those few nodes will be big server farms. The rest will be client nodes that only do transactions and don’t generate.",
              70: "There's more work to do on DoS, but I'm doing a quick build of what I have so far in case it's needed, before venturing into more complex ideas."}

    return quotes.get(random_integer)


def get_quote_of_a_bitcoiner(random_integer):
    quotes = {1:  "I had made an attempt to create my own proof of work based currency, called RPOW. So I found Bitcoin facinating. (Hal Finney)",
              2:  "Today, Satoshi’s true identity has become a mystery. But at the time, I thought I was dealing with a young man of Japanese ancestry who was very smart and sincere (Hal Finney)",
              3:  "As the price climbed up to real money, I transferred the coins into an offline wallet, where hopefully they’ll be worth somethingto my heirs. (Hal Finney)",
              4:  "",
              5:  "",
              6:  "",
              7:  "",
              8:  "",
              9:  "",
              10: "",
              11: "",
              12: "",
              13: "",
              14: "",
              15: "",
              16: "",
              17: "",
              18: "",
              19: "",
              20: "",
              21: "",
              22: "",
              23: "",
              24: "",
              25: "",
              26: "",
              27: "",
              28: "",
              29: "",
              30: "",
              31: "",
              32: "",
              33: "",
              34: ""}

def get_quote_of_history_of_digital_money(random_integer):
    quotes = {1:  "",
              2:  "",
              3:  "",
              4:  "",
              5:  "",
              6:  "",
              7:  "",
              8:  "",
              9:  "",
              10: "",
              11: "",
              12: "",
              13: "",
              14: "",
              15: "",
              16: "",
              17: "",
              18: "",
              19: "",
              20: "",
              21: "",
              22: "",
              23: "",
              24: "",
              25: "",
              26: "",
              27: "",
              28: "",
              29: "",
              30: "",
              31: "",
              32: "",
              33: "",
              34: ""}
